### ISSUE TITLE
About page not working

### ISSUE THREAD

**Issue by Mrrobinpatel** [Lalesh-Paudel/Bookmark-Management-System#10]
![collab](https://user-images.githubusercontent.com/82646959/118527190-c41e5e00-b760-11eb-8e65-521b7e9a42c6.PNG)

**Comment by Mrrobinpatel** [comment]
An error occurred during the attempt to open about page and leads back to the main design

**Comment by SparrowARK** [comment]
![image](https://user-images.githubusercontent.com/59025774/119252462-23022e00-bbcc-11eb-985e-b713b0cf0c2a.png)
About Us page fixed
