### ISSUE TITLE
Get request error in Registration page

### ISSUE THREAD

**Issue by Roshan-cmd** [Lalesh-Paudel/Bookmark-Management-System#11]
Reverse for login is not found.Login is not a valid view function or pattern name.

![image](https://user-images.githubusercontent.com/81338765/118911441-e9b88c80-b945-11eb-808c-16092c6e5eca.png)

**Comment by pandey-manish-bit** [comment]
Now, the registration page can be opened by the user. Also, I have fixed the NoReverseMatch error. So, now the user can register by clicking the register button, and the user will be redirected to the login page as given in the attached screenshot.

![image](https://user-images.githubusercontent.com/81338815/119255395-513b3a00-bbdb-11eb-8444-b5b1530cd864.png)
![188745753_507680647249942_6373245542527252899_n](https://user-images.githubusercontent.com/81338815/119255419-762fad00-bbdb-11eb-841d-7c64689eff0f.png)
