### ISSUE TITLE
Missing of Login Button in the Navigation Panel 

### ISSUE THREAD

**Issue by pandey-manish-bit** [Lalesh-Paudel/Bookmark-Management-System#6]
The Login Button should be in replace of the Input button and the input button should be just below the 'Home' Navigation button.
![image](https://user-images.githubusercontent.com/81338815/118357765-6b519880-b59b-11eb-86cc-78f37d164889.png)

**Comment by SparrowARK** [comment]
![image](https://user-images.githubusercontent.com/59025774/118578517-f99c6900-b7ab-11eb-9009-947e705f7753.png)

Login button now showing and position of input and login fixed
