### ISSUE TITLE
Design error in Bookmark Input Panel Page

### ISSUE THREAD

**Issue by Lalesh-Paudel** [Lalesh-Paudel/Bookmark-Management-System#7]
There is design error in bookmark input panel page. 
CSS effect is not properly working.
Need to fixed it.
![image](https://user-images.githubusercontent.com/81338792/118358001-8375e780-b59c-11eb-80c1-58361012d66a.png)

**Comment by SparrowARK** [comment]
![image](https://user-images.githubusercontent.com/59025774/119253943-42508980-bbd3-11eb-973b-63d43660449e.png)
Fixed this issue
