### ISSUE TITLE
profile page not displaying

### ISSUE THREAD

**Issue by Roshan-cmd** [Lalesh-Paudel/Bookmark-Management-System#8]

**Comment by Roshan-cmd** [comment]
There is a error in the profile page. The profile page is not displaying properly which we need to fix it.
![image](https://user-images.githubusercontent.com/81338765/118371558-d5366600-b5cc-11eb-8285-3098016503b0.png)

**Comment by SparrowARK** [comment]
![image](https://user-images.githubusercontent.com/59025774/119252404-cdc61c80-bbcb-11eb-82dd-4a1bffd05111.png)
Issue is fixed
