### ISSUE TITLE
Feedback page not displaying

### ISSUE THREAD

**Issue by SparrowARK** [Lalesh-Paudel/Bookmark-Management-System#9]
![image](https://user-images.githubusercontent.com/59025774/118526416-f1b6d780-b75f-11eb-9520-8c358f8ce159.png)
 
Image is not loading and showing white blank page

**Comment by Mrrobinpatel** [comment]
Iam working on it

**Comment by np03a190308** [comment]
Thanks for providing the feedback page, @Mrrobinpatel. Now that I've linked your feedback page to the Django project, you can use it.

**Comment by SparrowARK** [comment]
![image](https://user-images.githubusercontent.com/59025774/119253927-264ce800-bbd3-11eb-8725-0a21d75fb575.png)
Robin fixed it
